nelmio_cors:
    defaults:
        allow_origin: ['*']   # à restreindre si besoin
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'DELETE', 'PUT']
        expose_headers: []
        max_age: 3600
    paths:
        '^/': ~
